cleaning_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: true
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 1.0
   inflation_radius: 0.35
   map_type: costmap

cleaning_plan_nodehandle:   
   size_of_cell: 4
   grid_covered_value: 200
