obstacle_range: 2.5   #2.5
raytrace_range: 3.0  #3.0
inflation_radius: 0.35 ##peng zhang ban jing
footprint: [[0.35, 0.35], [0.35, -0.35], [-0.35, -0.35], [-0.35, 0.35]]
footprint_inflation: 0.01
#robot_radius: 0.28  #0.175
max_obstacle_height: 3.0
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}

# if set to false,then obstacle layer take unknow space to be free.
obstacle_layer:
   track_unknown_space: true
